#!/bin/sh
################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.11
##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
##  /   /         Filename : simulate_ncsim.sh
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script SIMULATE_NCSIM.SH
## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard
##
##***************************** Beginning of Script ***************************

                
#Ensure the follwoing
#The library paths for UNISIMS_VER, SIMPRIMS_VER, XILINXCORELIB_VER,
#UNISIM, SIMPRIM, XILINXCORELIB are set correctly in the cds.lib and hdl.var files.
#Variables LMC_HOME and XILINX are set 
#Define the mapping for the work library in cds.lib file. DEFINE work ./work

mkdir work
##MGT Wrapper
ncvlog -work work   ../../../s6_gtpwizard_v1_11_tile.v;
ncvlog -work work   ../../../s6_gtpwizard_v1_11.v;

 
##Clock Modules 
ncvlog -work work  ../../example_design/mgt_usrclk_source.v;

##Example Design modules
ncvlog -work work   ../../example_design/frame_gen.v;
ncvlog -work work   ../../example_design/frame_check.v;
ncvlog -work work   ../../example_design/s6_gtpwizard_v1_11_top.v;
ncvlog -work work   ../demo_tb.v;

##Other modules
ncvlog -work work $XILINX/verilog/src/glbl.v;

##Elaborate Design
ncelab -TIMESCALE 1ns/1ps -ACCESS +rw work.DEMO_TB work.glbl

##Run simulation
ncsim work.DEMO_TB -input @"simvision -input wave_ncsim.sv"

