#!/bin/sh
################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.11
##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
##  /   /         Filename : simulate_isim.sh
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script SIMULATE_ISIM.SH
## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard

##***************************** Beginning of Script ***************************

        
mkdir work
##MGT Wrapper
vlogcomp -work work  ../../../s6_gtpwizard_v1_11_tile.v;
vlogcomp -work work  ../../../s6_gtpwizard_v1_11.v;

 
##Clock Modules 
vlogcomp -work work  ../../example_design/mgt_usrclk_source.v;

##Example Design modules
vlogcomp -work work  ../../example_design/frame_gen.v;
vlogcomp -work work  ../../example_design/frame_check.v;
vlogcomp -work work  ../../example_design/s6_gtpwizard_v1_11_top.v;


##Other modules
vlogcomp -work work  $XILINX/verilog/src/glbl.v;

##Testbench file
vlogcomp -work work  ../demo_tb.v;


#Compile and link source files
fuse work.DEMO_TB work.glbl -L unisims_ver -L secureip -o demo_tb.exe

##--Generate waveform trace--##
./demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim

