# ODMB7 UltraScale FPGA Pinout XDC file
# ----------------------------------------------------------------------------------------------------------------------
# Location constraints for differential reference clock buffers
# Outline/section title:
# - DCFEB JTAG/control pins
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# DCFEB JTAG / HD50 pins
# ----------------------------------------------------------------------------------------------------------------------
set_property PACKAGE_PIN     F15        [get_ports DCFEB_TCK_P[1]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_P[1]]
set_property PACKAGE_PIN     F14        [get_ports DCFEB_TCK_N[1]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_N[1]]
set_property PACKAGE_PIN     D19        [get_ports DCFEB_TCK_P[2]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_P[2]]
set_property PACKAGE_PIN     D18        [get_ports DCFEB_TCK_N[2]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_N[2]]
set_property PACKAGE_PIN     D14        [get_ports DCFEB_TCK_P[3]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_P[3]]
set_property PACKAGE_PIN     C14        [get_ports DCFEB_TCK_N[3]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_N[3]]
set_property PACKAGE_PIN     E15        [get_ports DCFEB_TCK_P[4]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_P[4]]
set_property PACKAGE_PIN     D15        [get_ports DCFEB_TCK_N[4]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_N[4]]
set_property PACKAGE_PIN     B17        [get_ports DCFEB_TCK_P[5]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_P[5]]
set_property PACKAGE_PIN     B16        [get_ports DCFEB_TCK_N[5]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TCK_N[5]]
set_property PACKAGE_PIN     A19        [get_ports DCFEB_TMS_P]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TMS_P]
set_property PACKAGE_PIN     A18        [get_ports DCFEB_TMS_N]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TMS_N]
set_property PACKAGE_PIN     B14        [get_ports DCFEB_TDI_P]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDI_P]
set_property PACKAGE_PIN     A14        [get_ports DCFEB_TDI_N]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDI_N]

set_property PACKAGE_PIN     F23        [get_ports DCFEB_TDO_P[1]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_P[1]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_P[1]]
set_property PACKAGE_PIN     F24        [get_ports DCFEB_TDO_N[1]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_N[1]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_N[1]]
set_property PACKAGE_PIN     D20        [get_ports DCFEB_TDO_P[2]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_P[2]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_P[2]]
set_property PACKAGE_PIN     D21        [get_ports DCFEB_TDO_N[2]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_N[2]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_N[2]]
set_property PACKAGE_PIN     G20        [get_ports DCFEB_TDO_P[3]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_P[3]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_P[3]]
set_property PACKAGE_PIN     F20        [get_ports DCFEB_TDO_N[3]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_N[3]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_N[3]]
set_property PACKAGE_PIN     G24        [get_ports DCFEB_TDO_P[4]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_P[4]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_P[4]]
set_property PACKAGE_PIN     F25        [get_ports DCFEB_TDO_N[4]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_N[4]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_N[4]]
set_property PACKAGE_PIN     G22        [get_ports DCFEB_TDO_P[5]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_P[5]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_P[5]]
set_property PACKAGE_PIN     F22        [get_ports DCFEB_TDO_N[5]]
set_property IOSTANDARD      LVDS       [get_ports DCFEB_TDO_N[5]]
set_property DIFF_TERM_ADV   TERM_100   [get_ports DCFEB_TDO_N[5]]

set_property PACKAGE_PIN     G19        [get_ports DCFEB_DONE[1]]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_DONE[1]]
set_property PACKAGE_PIN     F19        [get_ports DCFEB_DONE[2]]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_DONE[2]]
set_property PACKAGE_PIN     G15        [get_ports DCFEB_DONE[3]]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_DONE[3]]
set_property PACKAGE_PIN     G14        [get_ports DCFEB_DONE[4]]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_DONE[4]]
set_property PACKAGE_PIN     F18        [get_ports DCFEB_DONE[5]]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_DONE[5]]

# DCFEB test pins
set_property PACKAGE_PIN     D8         [get_ports RESYNC_P]
set_property IOSTANDARD      LVDS       [get_ports RESYNC_P]
set_property PACKAGE_PIN     C8         [get_ports RESYNC_N]
set_property IOSTANDARD      LVDS       [get_ports RESYNC_N]
set_property PACKAGE_PIN     B15        [get_ports BC0_P]
set_property IOSTANDARD      LVDS       [get_ports BC0_P]
set_property PACKAGE_PIN     A15        [get_ports BC0_N]
set_property IOSTANDARD      LVDS       [get_ports BC0_N]
set_property PACKAGE_PIN     E10        [get_ports INJPLS_P]
set_property IOSTANDARD      LVDS       [get_ports INJPLS_P]
set_property PACKAGE_PIN     D10        [get_ports INJPLS_N]
set_property IOSTANDARD      LVDS       [get_ports INJPLS_N]
set_property PACKAGE_PIN     B10        [get_ports EXTPLS_P]
set_property IOSTANDARD      LVDS       [get_ports EXTPLS_P]
set_property PACKAGE_PIN     A10        [get_ports EXTPLS_N]
set_property IOSTANDARD      LVDS       [get_ports EXTPLS_N]
set_property PACKAGE_PIN     C16        [get_ports CFEB_OUT_EN_B]
set_property IOSTANDARD      LVCMOS18   [get_ports CFEB_OUT_EN_B]
set_property PACKAGE_PIN     A17        [get_ports DCFEB_REPORG_B]
set_property IOSTANDARD      LVCMOS18   [get_ports DCFEB_REPORG_B]

# L1A pins
set_property PACKAGE_PIN     B9         [get_ports L1A_P]
set_property IOSTANDARD      LVDS       [get_ports L1A_P]
set_property PACKAGE_PIN     A9         [get_ports L1A_N]
set_property IOSTANDARD      LVDS       [get_ports L1A_N]
set_property PACKAGE_PIN     L8         [get_ports L1A_MATCH_P[1]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[1]]
set_property PACKAGE_PIN     K8         [get_ports L1A_MATCH_N[1]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[1]]
set_property PACKAGE_PIN     D13        [get_ports L1A_MATCH_P[2]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[2]]
set_property PACKAGE_PIN     C13        [get_ports L1A_MATCH_N[2]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[2]]
set_property PACKAGE_PIN     A13        [get_ports L1A_MATCH_P[3]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[3]]
set_property PACKAGE_PIN     A12        [get_ports L1A_MATCH_N[3]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[3]]
set_property PACKAGE_PIN     F13        [get_ports L1A_MATCH_P[4]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[4]]
set_property PACKAGE_PIN     E13        [get_ports L1A_MATCH_N[4]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[4]]
set_property PACKAGE_PIN     C11        [get_ports L1A_MATCH_P[5]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[5]]
set_property PACKAGE_PIN     B11        [get_ports L1A_MATCH_N[5]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[5]]
set_property PACKAGE_PIN     C12        [get_ports L1A_MATCH_P[6]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[6]]
set_property PACKAGE_PIN     B12        [get_ports L1A_MATCH_N[6]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[6]]
set_property PACKAGE_PIN     E11        [get_ports L1A_MATCH_P[7]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_P[7]]
set_property PACKAGE_PIN     D11        [get_ports L1A_MATCH_N[7]]
set_property IOSTANDARD      LVDS       [get_ports L1A_MATCH_N[7]]
