////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 1.12
//  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard 
//  /   /         Filename : gtx_alct_link_test_top.v
// /___/   /\      
// \   \  /  \ 
//  \___\/\___\ 
//
//
// Module gtx_alct_link_test_top
// Generated by Xilinx Virtex-6 FPGA GTX Transceiver Wizard
// 
// 
// (c) Copyright 2009-2011 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1


//***********************************Entity Declaration************************

module gtx_alct_link_test_top #
(
    parameter EXAMPLE_CONFIG_INDEPENDENT_LANES          =   0,   //configuration for frame gen and check
    parameter EXAMPLE_LANE_WITH_START_CHAR              =   0,    // specifies lane with unique start frame char
    parameter EXAMPLE_WORDS_IN_BRAM                     =   512,  // specifies amount of data in BRAM
    parameter EXAMPLE_SIM_GTXRESET_SPEEDUP              =   1,    // simulation setting for GTX SecureIP model
    parameter EXAMPLE_USE_CHIPSCOPE                     =   1     // Set to 1 to use Chipscope to drive resets
)
(

    //input wire  Q1_CLK0_MGTREFCLK_PAD_N_IN,
    //input wire  Q1_CLK0_MGTREFCLK_PAD_P_IN,
    input wire  Q1_CLK0_REFCLK_I,
    input wire  GTXTXRESET_IN,
    input wire  GTXRXRESET_IN,
    //output wire TRACK_DATA_OUT,
    output wire [6:1] LEDR,
    output wire [6:1] LEDG,
    input  wire [1:0]   RXN_IN,
    input  wire [1:0]   RXP_IN,
    output wire [1:0]   TXN_OUT,
    output wire [1:0]   TXP_OUT
);


//************************** Register Declarations ****************************

//    reg     [1:0]   TXN_OUT;
//    reg     [1:0]   TXP_OUT;

    reg     [84:0]  ila_in_r;

    reg             gtx0_txresetdone_r;
    reg             gtx0_txresetdone_r2;
// * max_fanout = 1 *
    reg             gtx0_rxresetdone_i_r;
    reg             gtx0_rxresetdone_r;
    reg             gtx0_rxresetdone_r2;
    reg             gtx0_rxresetdone_r3;
    reg             gtx1_txresetdone_r;
    reg             gtx1_txresetdone_r2;
// * max_fanout = 1 *
    reg             gtx1_rxresetdone_i_r;
    reg             gtx1_rxresetdone_r;
    reg             gtx1_rxresetdone_r2;
    reg             gtx1_rxresetdone_r3;
    //------------------------ MGT Wrapper Wires ------------------------------
    //________________________________________________________________________
    //________________________________________________________________________
    //GTX0   (X0Y0)

    //---------------------- Loopback and Powerdown Ports ----------------------
    wire    [2:0]   gtx0_loopback_i;
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    wire    [1:0]   gtx0_rxchariscomma_i;
    wire    [1:0]   gtx0_rxcharisk_i;
    wire    [1:0]   gtx0_rxdisperr_i;
    wire    [1:0]   gtx0_rxnotintable_i;
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    wire            gtx0_rxchanbondseq_i;
    wire            gtx0_rxenchansync_i;
    //------------- Receive Ports - Comma Detection and Alignment --------------
    wire            gtx0_rxcommadet_i;
    wire            gtx0_rxenmcommaalign_i;
    wire            gtx0_rxenpcommaalign_i;
    //----------------- Receive Ports - RX Data Path interface -----------------
    wire    [15:0]  gtx0_rxdata_i;
    wire            gtx0_rxrecclk_i;
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    wire    [2:0]   gtx0_rxeqmix_i;
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    wire    [2:0]   gtx0_rxbufstatus_i;
    wire            gtx0_rxchanisaligned_i;
    wire            gtx0_rxchanrealign_i;
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    wire            gtx0_grefclkrx_i;
    wire            gtx0_gtxrxreset_i;
    wire    [1:0]   gtx0_northrefclkrx_i;
    wire            gtx0_perfclkrx_i;
    wire            gtx0_pllrxreset_i;
    wire            gtx0_rxplllkdet_i;
    wire    [2:0]   gtx0_rxpllrefseldy_i;
    wire            gtx0_rxresetdone_i;
    wire    [1:0]   gtx0_southrefclkrx_i;
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    wire    [1:0]   gtx0_txcharisk_i;
    //---------------- Transmit Ports - TX Data Path interface -----------------
    wire    [15:0]  gtx0_txdata_i;
    wire            gtx0_txoutclk_i;
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    wire    [3:0]   gtx0_txdiffctrl_i;
    wire    [4:0]   gtx0_txpostemphasis_i;
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    wire    [3:0]   gtx0_txpreemphasis_i;
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    wire            gtx0_grefclktx_i;
    wire            gtx0_gtxtxreset_i;
    wire    [1:0]   gtx0_northrefclktx_i;
    wire            gtx0_perfclktx_i;
    wire    [1:0]   gtx0_southrefclktx_i;
    wire    [2:0]   gtx0_txpllrefseldy_i;
    wire            gtx0_txresetdone_i;


    //________________________________________________________________________
    //________________________________________________________________________
    //GTX1   (X0Y4)

    //---------------------- Loopback and Powerdown Ports ----------------------
    wire    [2:0]   gtx1_loopback_i;
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    wire    [1:0]   gtx1_rxchariscomma_i;
    wire    [1:0]   gtx1_rxcharisk_i;
    wire    [1:0]   gtx1_rxdisperr_i;
    wire    [1:0]   gtx1_rxnotintable_i;
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    wire            gtx1_rxchanbondseq_i;
    wire            gtx1_rxenchansync_i;
    //------------- Receive Ports - Comma Detection and Alignment --------------
    wire            gtx1_rxcommadet_i;
    wire            gtx1_rxenmcommaalign_i;
    wire            gtx1_rxenpcommaalign_i;
    //----------------- Receive Ports - RX Data Path interface -----------------
    wire    [15:0]  gtx1_rxdata_i;
    wire            gtx1_rxrecclk_i;
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    wire    [2:0]   gtx1_rxeqmix_i;
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    wire    [2:0]   gtx1_rxbufstatus_i;
    wire            gtx1_rxchanisaligned_i;
    wire            gtx1_rxchanrealign_i;
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    wire            gtx1_grefclkrx_i;
    wire            gtx1_gtxrxreset_i;
    wire    [1:0]   gtx1_northrefclkrx_i;
    wire            gtx1_perfclkrx_i;
    wire            gtx1_pllrxreset_i;
    wire            gtx1_rxplllkdet_i;
    wire    [2:0]   gtx1_rxpllrefseldy_i;
    wire            gtx1_rxresetdone_i;
    wire    [1:0]   gtx1_southrefclkrx_i;
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    wire    [1:0]   gtx1_txcharisk_i;
    //---------------- Transmit Ports - TX Data Path interface -----------------
    wire    [15:0]  gtx1_txdata_i;
    wire            gtx1_txoutclk_i;
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    wire    [3:0]   gtx1_txdiffctrl_i;
    wire    [4:0]   gtx1_txpostemphasis_i;
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    wire    [3:0]   gtx1_txpreemphasis_i;
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    wire            gtx1_grefclktx_i;
    wire            gtx1_gtxtxreset_i;
    wire    [1:0]   gtx1_northrefclktx_i;
    wire            gtx1_perfclktx_i;
    wire    [1:0]   gtx1_southrefclktx_i;
    wire    [2:0]   gtx1_txpllrefseldy_i;
    wire            gtx1_txresetdone_i;



    //------------------------ Channel Bonding Wires ---------------------------
    wire    [3:0]   gtx0_rxchbondo_i;
    wire    [3:0]   gtx1_rxchbondo_i;

    //----------------------------- Global Signals -----------------------------
    wire            gtx0_tx_system_reset_c;
    wire            gtx0_rx_system_reset_c;
    wire            gtx1_tx_system_reset_c;
    wire            gtx1_rx_system_reset_c;
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [7:0]   tied_to_vcc_vec_i;
    wire            drp_clk_in_i;

    //--------------------------- User Clocks ---------------------------------
    wire            gtx0_txusrclk2_i;
    wire            gtx0_rxusrclk2_i;
    wire            gtx1_rxusrclk2_i;


    //--------------------------- Reference Clocks ----------------------------
    
    //wire            q1_clk0_refclk_i;
    wire            q1_clk0_refclk_i_bufg;
    //--------------------- Frame check/gen Module Signals --------------------
    wire            gtx0_matchn_i;
    
    wire    [1:0]   gtx0_txcharisk_float_i;
    
    wire    [23:0]  gtx0_txdata_float_i;
    
    
    wire            gtx0_block_sync_i;
    wire            gtx0_track_data_i;
    wire    [7:0]   gtx0_error_count_i;
    wire            gtx0_frame_check_reset_i;
    wire            gtx0_inc_in_i;
    wire            gtx0_inc_out_i;
    wire    [15:0]  gtx0_unscrambled_data_i;

    wire            gtx1_matchn_i;
    
    wire    [1:0]   gtx1_txcharisk_float_i;
    
    wire    [23:0]  gtx1_txdata_float_i;
    
    
    wire            gtx1_block_sync_i;
    wire            gtx1_track_data_i;
    wire    [7:0]   gtx1_error_count_i;
    wire            gtx1_frame_check_reset_i;
    wire            gtx1_inc_in_i;
    wire            gtx1_inc_out_i;
    wire    [15:0]  gtx1_unscrambled_data_i;

    wire            reset_on_data_error_i;
    wire            track_data_out_i;


    //--------------------- Chipscope Signals ---------------------------------

    wire    [35:0]  tx_data_vio_control_i;
    wire    [35:0]  rx_data_vio_control_i;
    wire    [35:0]  shared_vio_control_i;
    wire    [35:0]  ila_control_i;
    wire    [31:0]  tx_data_vio_async_in_i;
    wire    [31:0]  tx_data_vio_sync_in_i;
    wire    [31:0]  tx_data_vio_async_out_i;
    wire    [31:0]  tx_data_vio_sync_out_i;
    wire    [31:0]  rx_data_vio_async_in_i;
    wire    [31:0]  rx_data_vio_sync_in_i;
    wire    [31:0]  rx_data_vio_async_out_i;
    wire    [31:0]  rx_data_vio_sync_out_i;
    wire    [31:0]  shared_vio_in_i;
    wire    [31:0]  shared_vio_out_i;
    wire    [84:0]  ila_in_i;

    wire    [31:0]  gtx0_tx_data_vio_async_in_i;
    wire    [31:0]  gtx0_tx_data_vio_sync_in_i;
    wire    [31:0]  gtx0_tx_data_vio_async_out_i;
    wire    [31:0]  gtx0_tx_data_vio_sync_out_i;
    wire    [31:0]  gtx0_rx_data_vio_async_in_i;
    wire    [31:0]  gtx0_rx_data_vio_sync_in_i;
    wire    [31:0]  gtx0_rx_data_vio_async_out_i;
    wire    [31:0]  gtx0_rx_data_vio_sync_out_i;
    wire    [84:0]  gtx0_ila_in_i;

    wire    [31:0]  gtx1_tx_data_vio_async_in_i;
    wire    [31:0]  gtx1_tx_data_vio_sync_in_i;
    wire    [31:0]  gtx1_tx_data_vio_async_out_i;
    wire    [31:0]  gtx1_tx_data_vio_sync_out_i;
    wire    [31:0]  gtx1_rx_data_vio_async_in_i;
    wire    [31:0]  gtx1_rx_data_vio_sync_in_i;
    wire    [31:0]  gtx1_rx_data_vio_async_out_i;
    wire    [31:0]  gtx1_rx_data_vio_sync_out_i;
    wire    [84:0]  gtx1_ila_in_i;


    wire            gtxtxreset_i;
    wire            gtxrxreset_i;
    wire            mux_sel_i;
    wire    [148:0] gtx0_rx_data_to_fifo_i;
    wire    [148:0] gtx0_rx_data_from_fifo_i;
    wire    [31:0]  gtx0_rx_data_fifo_vio_async_in_i;
    wire    [31:0]  gtx0_rx_data_fifo_vio_sync_in_i;
    wire    [84:0]  gtx0_fifo_ila_in_i;
    wire    [148:0] gtx1_rx_data_to_fifo_i;
    wire    [148:0] gtx1_rx_data_from_fifo_i;
    wire    [31:0]  gtx1_rx_data_fifo_vio_async_in_i;
    wire    [31:0]  gtx1_rx_data_fifo_vio_sync_in_i;
    wire    [84:0]  gtx1_fifo_ila_in_i;

    wire            user_tx_reset_i;
    wire            user_rx_reset_i;
    wire            tx_vio_clk_i;
    wire            tx_vio_clk_mux_out_i;    
    wire            rx_vio_ila_clk_i;
    wire            rx_vio_ila_clk_mux_out_i;
    wire  [1:0]     q1_clk0_refclk_i_i;

//**************************** Main Body of Code *******************************

    //  Static signal Assigments    
    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 8'hff;
    assign gtx0_grefclktx_i             = tied_to_ground_i;
    assign gtx0_grefclkrx_i             = tied_to_ground_i;
    assign gtx0_perfclktx_i             = tied_to_ground_i;
    assign gtx0_perfclkrx_i             = tied_to_ground_i;
    assign gtx0_northrefclktx_i         = tied_to_ground_vec_i[1:0];
    assign gtx0_northrefclkrx_i         = tied_to_ground_vec_i[1:0];
    assign gtx0_southrefclktx_i         = tied_to_ground_vec_i[1:0];
    assign gtx0_southrefclkrx_i         = tied_to_ground_vec_i[1:0];
    assign gtx1_grefclktx_i             = tied_to_ground_i;
    assign gtx1_grefclkrx_i             = tied_to_ground_i;
    assign gtx1_perfclktx_i             = tied_to_ground_i;
    assign gtx1_perfclkrx_i             = tied_to_ground_i;
    assign gtx1_northrefclktx_i         = tied_to_ground_vec_i[1:0];
    assign gtx1_northrefclkrx_i         = tied_to_ground_vec_i[1:0];
    assign gtx1_southrefclktx_i         = tied_to_ground_vec_i[1:0];
    assign gtx1_southrefclkrx_i         = tied_to_ground_vec_i[1:0];



    //---------------------Dedicated GTX Reference Clock Inputs ---------------
    // The dedicated reference clock inputs you selected in the GUI are implemented using
    // IBUFDS_GTXE1 instances.
    //
    // In the UCF file for this example design, you will see that each of
    // these IBUFDS_GTXE1 instances has been LOCed to a particular set of pins. By LOCing to these
    // locations, we tell the tools to use the dedicated input buffers to the GTX reference
    // clock network, rather than general purpose IOs. To select other pins, consult the 
    // Implementation chapter of UG___, or rerun the wizard.
    //
    // This network is the highest performace (lowest jitter) option for providing clocks
    // to the GTX transceivers.
    
    //IBUFDS_GTXE1 q1_clk0_refclk_ibufds_i
    //(
    //    .O                              (Q1_CLK0_REFCLK_I),
    //    .ODIV2                          (),
    //    .CEB                            (tied_to_ground_i),
    //    .I                              (Q1_CLK0_MGTREFCLK_PAD_P_IN),
    //    .IB                             (Q1_CLK0_MGTREFCLK_PAD_N_IN)
    //);

    assign q1_clk0_refclk_i_i = {1'b0,Q1_CLK0_REFCLK_I};
 
    

    BUFG q1_clk0_refclk_bufg_i
    (
        .I                              (Q1_CLK0_REFCLK_I),
        .O                              (q1_clk0_refclk_i_bufg)
    );



    //--------------------------------- User Clocks ---------------------------
    
    // The clock resources in this section were added based on userclk source selections on
    // the Latency, Buffering, and Clocking page of the GUI. A few notes about user clocks:
    // * The userclk and userclk2 for each GTX datapath (TX and RX) must be phase aligned to 
    //   avoid data errors in the fabric interface whenever the datapath is wider than 10 bits
    // * To minimize clock resources, you can share clocks between GTXs. GTXs using the same frequency
    //   or multiples of the same frequency can be accomadated using MMCMs. Use caution when
    //   using RXRECCLK as a clock source, however - these clocks can typically only be shared if all
    //   the channels using the clock are receiving data from TX channels that share a reference clock 
    //   source with each other.

    BUFG txoutclk_bufg0_i
    (
        .I                              (gtx0_txoutclk_i),
        .O                              (gtx0_txusrclk2_i)
    );


    BUFG rxrecclk_bufg1_i
    (
        .I                              (gtx0_rxrecclk_i),
        .O                              (gtx0_rxusrclk2_i)
    );


    BUFG rxrecclk_bufg2_i
    (
        .I                              (gtx1_rxrecclk_i),
        .O                              (gtx1_rxusrclk2_i)
    );






    //--------------------------- The GTX Wrapper -----------------------------
    
    // Use the instantiation template in the example directory to add the GTX wrapper to your design.
    // In this example, the wrapper is wired up for basic operation with a frame generator and frame 
    // checker. The GTXs will reset, then attempt to align and transmit data. If channel bonding is 
    // enabled, bonding should occur after alignment.
    
    gtx_alct_link_test #
    (
        .WRAPPER_SIM_GTXRESET_SPEEDUP   (EXAMPLE_SIM_GTXRESET_SPEEDUP)
    )
    gtx_alct_link_test_i
    (
 
 

        //_____________________________________________________________________
        //_____________________________________________________________________
        //GTX0  (X0Y0)
        //---------------------- Loopback and Powerdown Ports ----------------------
        .GTX0_LOOPBACK_IN               (gtx0_loopback_i),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .GTX0_RXCHARISCOMMA_OUT         (gtx0_rxchariscomma_i),
        .GTX0_RXCHARISK_OUT             (gtx0_rxcharisk_i),
        .GTX0_RXDISPERR_OUT             (gtx0_rxdisperr_i),
        .GTX0_RXNOTINTABLE_OUT          (gtx0_rxnotintable_i),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .GTX0_RXCHANBONDSEQ_OUT         (gtx0_rxchanbondseq_i),
        .GTX0_RXCHBONDI_IN              (gtx1_rxchbondo_i),
        .GTX0_RXCHBONDLEVEL_IN          (3'b000),
        .GTX0_RXCHBONDMASTER_IN         (tied_to_ground_i),
        .GTX0_RXCHBONDO_OUT             (gtx0_rxchbondo_i),
        .GTX0_RXCHBONDSLAVE_IN          (tied_to_vcc_i),
        .GTX0_RXENCHANSYNC_IN           (gtx0_rxenchansync_i),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .GTX0_RXCOMMADET_OUT            (gtx0_rxcommadet_i),
        .GTX0_RXENMCOMMAALIGN_IN        (gtx0_rxenmcommaalign_i),
        .GTX0_RXENPCOMMAALIGN_IN        (gtx0_rxenpcommaalign_i),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTX0_RXDATA_OUT                (gtx0_rxdata_i),
        .GTX0_RXRECCLK_OUT              (gtx0_rxrecclk_i),
        .GTX0_RXUSRCLK2_IN              (gtx0_rxusrclk2_i),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTX0_RXEQMIX_IN                (gtx0_rxeqmix_i),
        .GTX0_RXN_IN                    (RXN_IN[0]),
        .GTX0_RXP_IN                    (RXP_IN[0]),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .GTX0_RXBUFSTATUS_OUT           (gtx0_rxbufstatus_i),
        .GTX0_RXCHANISALIGNED_OUT       (gtx0_rxchanisaligned_i),
        .GTX0_RXCHANREALIGN_OUT         (gtx0_rxchanrealign_i),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTX0_GREFCLKRX_IN              (gtx0_grefclkrx_i),
        .GTX0_GTXRXRESET_IN             (gtx0_gtxrxreset_i),
        .GTX0_MGTREFCLKRX_IN            (q1_clk0_refclk_i_i),
        .GTX0_NORTHREFCLKRX_IN          (gtx0_northrefclkrx_i),
        .GTX0_PERFCLKRX_IN              (gtx0_perfclkrx_i),
        .GTX0_PLLRXRESET_IN             (gtx0_pllrxreset_i),
        .GTX0_RXPLLLKDET_OUT            (gtx0_rxplllkdet_i),
        .GTX0_RXPLLREFSELDY_IN          (gtx0_rxpllrefseldy_i),
        .GTX0_RXRESETDONE_OUT           (gtx0_rxresetdone_i),
        .GTX0_SOUTHREFCLKRX_IN          (gtx0_southrefclkrx_i),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .GTX0_TXCHARISK_IN              (gtx0_txcharisk_i),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTX0_TXDATA_IN                 (gtx0_txdata_i),
        .GTX0_TXOUTCLK_OUT              (gtx0_txoutclk_i),
        .GTX0_TXUSRCLK2_IN              (gtx0_txusrclk2_i),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTX0_TXDIFFCTRL_IN             (gtx0_txdiffctrl_i),
        .GTX0_TXN_OUT                   (TXN_OUT[0]),
        .GTX0_TXP_OUT                   (TXP_OUT[0]),
        .GTX0_TXPOSTEMPHASIS_IN         (gtx0_txpostemphasis_i),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .GTX0_TXPREEMPHASIS_IN          (gtx0_txpreemphasis_i),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTX0_GREFCLKTX_IN              (gtx0_grefclktx_i),
        .GTX0_GTXTXRESET_IN             (gtx0_gtxtxreset_i),
        .GTX0_NORTHREFCLKTX_IN          (gtx0_northrefclktx_i),
        .GTX0_PERFCLKTX_IN              (gtx0_perfclktx_i),
        .GTX0_SOUTHREFCLKTX_IN          (gtx0_southrefclktx_i),
        .GTX0_TXPLLREFSELDY_IN          (gtx0_txpllrefseldy_i),
        .GTX0_TXRESETDONE_OUT           (gtx0_txresetdone_i),


 
 

        //_____________________________________________________________________
        //_____________________________________________________________________
        //GTX1  (X0Y4)
        //---------------------- Loopback and Powerdown Ports ----------------------
        .GTX1_LOOPBACK_IN               (gtx1_loopback_i),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .GTX1_RXCHARISCOMMA_OUT         (gtx1_rxchariscomma_i),
        .GTX1_RXCHARISK_OUT             (gtx1_rxcharisk_i),
        .GTX1_RXDISPERR_OUT             (gtx1_rxdisperr_i),
        .GTX1_RXNOTINTABLE_OUT          (gtx1_rxnotintable_i),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .GTX1_RXCHANBONDSEQ_OUT         (gtx1_rxchanbondseq_i),
        .GTX1_RXCHBONDI_IN              (tied_to_ground_vec_i[3:0]),
        .GTX1_RXCHBONDLEVEL_IN          (3'b001),
        .GTX1_RXCHBONDMASTER_IN         (tied_to_vcc_i),
        .GTX1_RXCHBONDO_OUT             (gtx1_rxchbondo_i),
        .GTX1_RXCHBONDSLAVE_IN          (tied_to_ground_i),
        .GTX1_RXENCHANSYNC_IN           (gtx1_rxenchansync_i),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .GTX1_RXCOMMADET_OUT            (gtx1_rxcommadet_i),
        .GTX1_RXENMCOMMAALIGN_IN        (gtx1_rxenmcommaalign_i),
        .GTX1_RXENPCOMMAALIGN_IN        (gtx1_rxenpcommaalign_i),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTX1_RXDATA_OUT                (gtx1_rxdata_i),
        .GTX1_RXRECCLK_OUT              (gtx1_rxrecclk_i),
        .GTX1_RXUSRCLK2_IN              (gtx1_rxusrclk2_i),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTX1_RXEQMIX_IN                (gtx1_rxeqmix_i),
        .GTX1_RXN_IN                    (RXN_IN[1]),
        .GTX1_RXP_IN                    (RXP_IN[1]),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .GTX1_RXBUFSTATUS_OUT           (gtx1_rxbufstatus_i),
        .GTX1_RXCHANISALIGNED_OUT       (gtx1_rxchanisaligned_i),
        .GTX1_RXCHANREALIGN_OUT         (gtx1_rxchanrealign_i),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTX1_GREFCLKRX_IN              (gtx1_grefclkrx_i),
        .GTX1_GTXRXRESET_IN             (gtx1_gtxrxreset_i),
        .GTX1_MGTREFCLKRX_IN            (q1_clk0_refclk_i_i),
        .GTX1_NORTHREFCLKRX_IN          (gtx1_northrefclkrx_i),
        .GTX1_PERFCLKRX_IN              (gtx1_perfclkrx_i),
        .GTX1_PLLRXRESET_IN             (gtx1_pllrxreset_i),
        .GTX1_RXPLLLKDET_OUT            (gtx1_rxplllkdet_i),
        .GTX1_RXPLLREFSELDY_IN          (gtx1_rxpllrefseldy_i),
        .GTX1_RXRESETDONE_OUT           (gtx1_rxresetdone_i),
        .GTX1_SOUTHREFCLKRX_IN          (gtx1_southrefclkrx_i),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .GTX1_TXCHARISK_IN              (gtx1_txcharisk_i),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTX1_TXDATA_IN                 (gtx1_txdata_i),
        .GTX1_TXOUTCLK_OUT              (gtx1_txoutclk_i),
        .GTX1_TXUSRCLK2_IN              (gtx0_txusrclk2_i),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTX1_TXDIFFCTRL_IN             (gtx1_txdiffctrl_i),
        .GTX1_TXN_OUT                   (TXN_OUT[1]),
        .GTX1_TXP_OUT                   (TXP_OUT[1]),
        .GTX1_TXPOSTEMPHASIS_IN         (gtx1_txpostemphasis_i),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .GTX1_TXPREEMPHASIS_IN          (gtx1_txpreemphasis_i),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTX1_GREFCLKTX_IN              (gtx1_grefclktx_i),
        .GTX1_GTXTXRESET_IN             (gtx1_gtxtxreset_i),
        .GTX1_NORTHREFCLKTX_IN          (gtx1_northrefclktx_i),
        .GTX1_PERFCLKTX_IN              (gtx1_perfclktx_i),
        .GTX1_SOUTHREFCLKTX_IN          (gtx1_southrefclktx_i),
        .GTX1_TXPLLREFSELDY_IN          (gtx1_txpllrefseldy_i),
        .GTX1_TXRESETDONE_OUT           (gtx1_txresetdone_i)


    );







    //------------------------ User Module Resets -----------------------------
    // All the User Modules i.e. FRAME_GEN, FRAME_CHECK and the sync modules
    // are held in reset till the RESETDONE goes high. 
    // The RESETDONE is registered a couple of times on *USRCLK2 and connected 
    // to the reset of the modules
    

    always @(posedge gtx0_rxusrclk2_i)
            gtx0_rxresetdone_i_r   <=   `DLY gtx0_rxresetdone_i;

    always @(posedge gtx0_rxusrclk2_i or negedge gtx0_rxresetdone_i_r)

    begin
        if (!gtx0_rxresetdone_i_r)
        begin
            gtx0_rxresetdone_r      <=   `DLY 1'b0;
            gtx0_rxresetdone_r2     <=   `DLY 1'b0;
        end
        else
        begin
            gtx0_rxresetdone_r      <=   `DLY gtx0_rxresetdone_i_r;
            gtx0_rxresetdone_r2     <=   `DLY gtx0_rxresetdone_r;
        end
    end

    always @(posedge gtx0_rxusrclk2_i)
            gtx0_rxresetdone_r3   <=   `DLY gtx0_rxresetdone_r2;
    
    
    always @(posedge gtx0_txusrclk2_i or negedge gtx0_txresetdone_i)

    begin
        if (!gtx0_txresetdone_i)
        begin
            gtx0_txresetdone_r    <=   `DLY 1'b0;
            gtx0_txresetdone_r2   <=   `DLY 1'b0;
        end
        else
        begin
            gtx0_txresetdone_r    <=   `DLY gtx0_txresetdone_i;
            gtx0_txresetdone_r2   <=   `DLY gtx0_txresetdone_r;
        end
    end

    always @(posedge gtx1_rxusrclk2_i)
            gtx1_rxresetdone_i_r   <=   `DLY gtx1_rxresetdone_i;

    always @(posedge gtx1_rxusrclk2_i or negedge gtx1_rxresetdone_i_r)

    begin
        if (!gtx1_rxresetdone_i_r)
        begin
            gtx1_rxresetdone_r      <=   `DLY 1'b0;
            gtx1_rxresetdone_r2     <=   `DLY 1'b0;
        end
        else
        begin
            gtx1_rxresetdone_r      <=   `DLY gtx1_rxresetdone_i_r;
            gtx1_rxresetdone_r2     <=   `DLY gtx1_rxresetdone_r;
        end
    end

    always @(posedge gtx1_rxusrclk2_i)
            gtx1_rxresetdone_r3   <=   `DLY gtx1_rxresetdone_r2;
    
    
    always @(posedge gtx0_txusrclk2_i or negedge gtx1_txresetdone_i)

    begin
        if (!gtx1_txresetdone_i)
        begin
            gtx1_txresetdone_r    <=   `DLY 1'b0;
            gtx1_txresetdone_r2   <=   `DLY 1'b0;
        end
        else
        begin
            gtx1_txresetdone_r    <=   `DLY gtx1_txresetdone_i;
            gtx1_txresetdone_r2   <=   `DLY gtx1_txresetdone_r;
        end
    end




    reg rxgood0, rxgood1;    
    initial rxgood0 = 2'b1;
    initial rxgood1 = 2'b1;

    reg [6:1] ledr_inner, ledg_inner;

    always @(posedge gtx0_rxusrclk2_i)

    begin
        if (gtx0_rxcharisk_i == 2'b01 ) begin
            if (gtx0_rxdata_i == 16'h503C) begin
                  rxgood0 <= 2'b0;
            end else begin
                  rxgood0 <= 2'b1;
            end
        end
        if (gtx1_rxcharisk_i == 2'b01) begin
            if (gtx1_rxdata_i == 16'h50BC) begin
                  rxgood1 <= 2'b0;
            end else begin
                  rxgood1 <= 2'b1;
            end
        end
   
        if (gtx0_rxnotintable_i != 2'b0) begin
            rxgood0 <= 2'b1;
        end 
        if (gtx1_rxnotintable_i != 2'b0) begin
            rxgood1 <= 2'b1;
        end

     ledr_inner[6] <= rxgood0;
     ledr_inner[5] <= rxgood0;
     ledr_inner[4] <= rxgood0;
     ledr_inner[3] <= rxgood0;
     ledr_inner[2] <= rxgood0;
     ledr_inner[1] <= rxgood0;

     ledg_inner[6] <= rxgood1;
     ledg_inner[5] <= rxgood1;
     ledg_inner[4] <= rxgood1;
     ledg_inner[3] <= rxgood1;
     ledg_inner[2] <= rxgood1;
     ledg_inner[1] <= rxgood1;

    end

    assign LEDR[6] = ledr_inner[6];
    assign LEDR[5] = ledr_inner[5];
    assign LEDR[4] = ledr_inner[4];
    assign LEDR[3] = ledr_inner[3];
    assign LEDR[2] = ledr_inner[2];
    assign LEDR[1] = ledr_inner[1];

    assign LEDG[6] = ledg_inner[6];
    assign LEDG[5] = ledg_inner[5];
    assign LEDG[4] = ledg_inner[4];
    assign LEDG[3] = ledg_inner[3];
    assign LEDG[2] = ledg_inner[2];
    assign LEDG[1] = ledg_inner[1];

    //---------------------------- Frame Generators ---------------------------
    // The example design uses Block RAM based frame generators to provide test
    // data to the GTXs for transmission. By default the frame generators are 
    // loaded with an incrementing data sequence that includes commas/alignment
    // characters for alignment. If your protocol uses channel bonding, the 
    // frame generator will also be preloaded with a channel bonding sequence.
    
    // You can modify the data transmitted by changing the INIT values of the frame
    // generator in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.

    FRAME_GEN #
    (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .MEM_00(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_01(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_02(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_03(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_04(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_05(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_06(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_07(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_08(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_09(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_0A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_0B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_0C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_0D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_0E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_0F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_10(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_11(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_12(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_13(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_14(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_15(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_16(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_17(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_18(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_19(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_1A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_1B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_1C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_1D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_1E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_1F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_20(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_21(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_22(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_23(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_24(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_25(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_26(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_27(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_28(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_29(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_2A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_2B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_2C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_2D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_2E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_2F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_30(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_31(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_32(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_33(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_34(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_35(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_36(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_37(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_38(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_39(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_3A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_3B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_3C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_3D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_3E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_3F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEMP_00(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_01(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_02(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_03(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_04(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_05(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_06(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_07(256'h3300000000000000000000000000000000000000000000000000000000000010)
    )
    gtx0_frame_gen
    (
        // User Interface
        .TX_DATA                        ({gtx0_txdata_float_i,gtx0_txdata_i}),
    
    
        .TX_CHARISK                     ({gtx0_txcharisk_float_i,gtx0_txcharisk_i}),
    
        // System Interface
        .USER_CLK                       (gtx0_txusrclk2_i),
        .SYSTEM_RESET                   (gtx0_tx_system_reset_c)
    );

    FRAME_GEN #
    (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .MEM_00(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_01(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_02(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_03(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_04(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_05(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_06(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_07(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_08(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_09(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_0A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_0B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_0C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_0D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_0E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_0F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_10(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_11(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_12(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_13(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_14(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_15(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_16(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_17(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_18(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_19(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_1A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_1B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_1C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_1D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_1E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_1F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_20(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_21(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_22(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_23(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_24(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_25(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_26(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_27(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_28(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_29(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_2A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_2B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_2C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_2D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_2E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_2F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_30(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_31(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_32(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_33(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_34(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_35(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_36(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_37(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_38(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_39(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_3A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_3B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_3C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_3D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_3E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_3F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEMP_00(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_01(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_02(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_03(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_04(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_05(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_06(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_07(256'h3300000000000000000000000000000000000000000000000000000000000010)
    )
    gtx1_frame_gen
    (
        // User Interface
        .TX_DATA                        ({gtx1_txdata_float_i,gtx1_txdata_i}),
    
    
        .TX_CHARISK                     ({gtx1_txcharisk_float_i,gtx1_txcharisk_i}),
    
        // System Interface
        .USER_CLK                       (gtx0_txusrclk2_i),
        .SYSTEM_RESET                   (gtx1_tx_system_reset_c)
    );


    //-------------------------------- Frame Checkers -------------------------
    // The example design uses Block RAM based frame checkers to verify incoming  
    // data. By default the frame generators are loaded with a data sequence that 
    // matches the outgoing sequence of the frame generators for the TX ports.
    
    // You can modify the expected data sequence by changing the INIT values of the frame
    // checkers in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.
    
    // When the frame checker receives data, it attempts to synchronise to the 
    // incoming pattern by looking for the first sequence in the pattern. Once it 
    // finds the first sequence, it increments through the sequence, and indicates an 
    // error whenever the next value received does not match the expected value.


    assign gtx0_frame_check_reset_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?reset_on_data_error_i:gtx0_matchn_i;

    // gtx0_frame_check0 is always connected to the lane with the start of char
    // and this lane starts off the data checking on all the other lanes. The INC_IN port is tied off
    assign gtx0_inc_in_i = 1'b0;

 
    FRAME_CHECK #
    (
        .RX_DATA_WIDTH(16),
        .RXCTRL_WIDTH(2),
        .USE_COMMA(1),
        .CHANBOND_SEQ_LEN(3),
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .CONFIG_INDEPENDENT_LANES(1),
        .START_OF_PACKET_CHAR(16'h02bc),
        .MEM_00(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_01(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_02(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_03(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_04(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_05(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_06(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_07(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_08(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_09(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_0A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_0B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_0C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_0D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_0E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_0F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_10(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_11(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_12(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_13(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_14(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_15(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_16(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_17(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_18(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_19(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_1A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_1B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_1C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_1D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_1E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_1F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_20(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_21(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_22(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_23(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_24(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_25(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_26(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_27(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_28(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_29(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_2A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_2B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_2C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_2D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_2E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_2F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_30(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_31(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_32(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_33(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_34(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_35(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_36(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_37(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_38(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_39(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_3A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_3B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_3C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_3D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_3E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_3F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEMP_00(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_01(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_02(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_03(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_04(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_05(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_06(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_07(256'h3300000000000000000000000000000000000000000000000000000000000010)
    )
    gtx0_frame_check
    (
        // MGT Interface
        .RX_DATA                        (gtx0_rxdata_i),
        .RXCTRL_IN                      (gtx0_rxcharisk_i),
        .RX_ENMCOMMA_ALIGN              (gtx0_rxenmcommaalign_i),
        .RX_ENPCOMMA_ALIGN              (gtx0_rxenpcommaalign_i),
        .RX_ENCHAN_SYNC                 (gtx0_rxenchansync_i),
        .RX_CHANBOND_SEQ                (gtx0_rxchanbondseq_i),
        // Control Interface
        .INC_IN                         (gtx0_inc_in_i),
        .INC_OUT                        (gtx0_inc_out_i),
        .PATTERN_MATCH_N                (gtx0_matchn_i),
        .RESET_ON_ERROR                 (gtx0_frame_check_reset_i),
        // System Interface
        .USER_CLK                       (gtx0_rxusrclk2_i),
        .SYSTEM_RESET                   (gtx0_rx_system_reset_c),
        .ERROR_COUNT                    (gtx0_error_count_i),
        .TRACK_DATA                     (gtx0_track_data_i)

    );

    

    assign gtx1_frame_check_reset_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?reset_on_data_error_i:gtx1_matchn_i;

    // in the "independent lanes" configuration, each of the lanes looks for the unique start char and
    // in this case, the INC_IN port is tied off.
    // Else, the data checking is triggered by the "master" lane
    assign gtx1_inc_in_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?gtx0_inc_out_i:1'b0;

 
    FRAME_CHECK #
    (
        .RX_DATA_WIDTH(16),
        .RXCTRL_WIDTH(2),
        .USE_COMMA(1),
        .CHANBOND_SEQ_LEN(3),
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .CONFIG_INDEPENDENT_LANES(EXAMPLE_CONFIG_INDEPENDENT_LANES),
        .START_OF_PACKET_CHAR(16'h02bc),
        .MEM_00(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_01(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_02(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_03(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_04(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_05(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_06(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_07(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_08(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_09(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_0A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_0B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_0C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_0D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_0E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_0F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_10(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_11(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_12(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_13(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_14(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_15(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_16(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_17(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_18(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_19(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_1A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_1B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_1C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_1D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_1E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_1F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_20(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_21(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_22(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_23(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_24(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_25(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_26(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_27(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_28(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_29(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_2A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_2B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_2C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_2D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_2E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_2F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_30(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_31(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_32(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_33(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_34(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_35(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_36(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_37(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEM_38(256'h00000e0d00000c0b00000a09000008070000060500000403000002bc00000100),
        .MEM_39(256'h00001e1d00001c1b00001a19000018170000161500001413000012110000100f),
        .MEM_3A(256'h00002e2d00002c2b00002a29000028270000262500002423000022210000201f),
        .MEM_3B(256'h00003e3d00003c3b00003a39000038370000363500003433000032310000302f),
        .MEM_3C(256'h00004e4d00004c4b00004a49000048470000464500004443000042410000403f),
        .MEM_3D(256'h00005e5d00005c5b00005a59000058570000565500005453000052510000504f),
        .MEM_3E(256'h00006e6d00006c6b00006a69000068670000666500006463000062610000605f),
        .MEM_3F(256'h0000dcfb0000fe1c00007a79000078770000767500007473000072710000706f),
        .MEMP_00(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_01(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_02(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_03(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_04(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_05(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_06(256'h3300000000000000000000000000000000000000000000000000000000000010),
        .MEMP_07(256'h3300000000000000000000000000000000000000000000000000000000000010)
    )
    gtx1_frame_check
    (
        // MGT Interface
        .RX_DATA                        (gtx1_rxdata_i),
        .RXCTRL_IN                      (gtx1_rxcharisk_i),
        .RX_ENMCOMMA_ALIGN              (gtx1_rxenmcommaalign_i),
        .RX_ENPCOMMA_ALIGN              (gtx1_rxenpcommaalign_i),
        .RX_ENCHAN_SYNC                 (gtx1_rxenchansync_i),
        .RX_CHANBOND_SEQ                (gtx1_rxchanbondseq_i),
        // Control Interface
        .INC_IN                         (gtx1_inc_in_i),
        .INC_OUT                        (gtx1_inc_out_i),
        .PATTERN_MATCH_N                (gtx1_matchn_i),
        .RESET_ON_ERROR                 (gtx1_frame_check_reset_i),
        // System Interface
        .USER_CLK                       (gtx1_rxusrclk2_i),
        .SYSTEM_RESET                   (gtx1_rx_system_reset_c),
        .ERROR_COUNT                    (gtx1_error_count_i),
        .TRACK_DATA                     (gtx1_track_data_i)

    );

    



    //assign TRACK_DATA_OUT = track_data_out_i;

    assign track_data_out_i = 
                                gtx0_track_data_i &
                                gtx1_track_data_i ;


    // To support channel bonding, the pattern_match_n ports of each frame_check module
    // are ORed together. Each frame checker has a parameter called CONFIG_INDEPENDANT_LANES
    // which, when set to 0, causes the frame generators to use the ORed match signals. This 
    // causes the lanes to synchronize and check a combined sequence across multiple blocks. If
    // CONFIG_INDEPENDANT_LANES is 1, each the lane will self-syncronize and check for errors
    // seperately from the other frame checkers.

    assign reset_on_data_error_i = gtx0_matchn_i |
                                         gtx1_matchn_i ;




    //--------------------------- Chipscope Connections -----------------------
    // When the example design is run in hardware, it uses chipscope to allow the
    // example design and GTX wrapper to be controlled and monitored. The 
    // EXAMPLE_USE_CHIPSCOPE parameter allows chipscope to be removed for simulation.
    
generate
if (EXAMPLE_USE_CHIPSCOPE==1) 
begin : chipscope

    // Shared VIO for all GTXs
    data_vio shared_vio_i
    (
      .control                          (shared_vio_control_i),
      .async_in                         (shared_vio_in_i),
      .async_out                        (shared_vio_out_i),
      .sync_in                          (tied_to_ground_vec_i[31:0]),
      .sync_out                         (),
      .clk                              (tied_to_ground_i)
    );

    // ICON for all VIOs
    icon i_icon
    (
      .control0                         (shared_vio_control_i),
      .control1                         (tx_data_vio_control_i),
      .control2                         (rx_data_vio_control_i),
      .control3                         (ila_control_i)
    );


    // TX VIO
    data_vio tx_data_vio_i
    (
      .control                          (tx_data_vio_control_i),
      .async_in                         (tx_data_vio_async_in_i),
      .async_out                        (tx_data_vio_async_out_i),
      .sync_in                          (tx_data_vio_sync_in_i),
      .sync_out                         (tx_data_vio_sync_out_i),
      .clk                              (gtx0_txusrclk2_i)
    );
    
    // RX VIO
    data_vio rx_data_vio_i
    (
      .control                          (rx_data_vio_control_i),
      .async_in                         (rx_data_vio_async_in_i),
      .async_out                        (rx_data_vio_async_out_i),
      .sync_in                          (rx_data_vio_sync_in_i),
      .sync_out                         (rx_data_vio_sync_out_i),
      .clk                              (rx_vio_ila_clk_i)
    );
    
    // RX ILA
    ila ila_i
    (
      .control                          (ila_control_i),
      .clk                              (rx_vio_ila_clk_i),
      .trig0                            (ila_in_i)
    );



    // The RX VIO and ILA uses GTX0's RXUSRCLK2
    assign  rx_vio_ila_clk_i = gtx0_rxusrclk2_i;

 
    assign gtx0_rx_data_to_fifo_i={gtx0_rx_data_vio_async_in_i,gtx0_rx_data_vio_sync_in_i,gtx0_ila_in_i};

    rx_phase_align_fifo rx_phase_align_fifo_0_i 
    (
        .rst(gtx0_rx_system_reset_c),
        .wr_clk(gtx0_rxusrclk2_i),
        .rd_clk(rx_vio_ila_clk_i),
        .din(gtx0_rx_data_to_fifo_i),  
        .wr_en(1'b1),
        .rd_en(1'b1),
        .dout(gtx0_rx_data_from_fifo_i),  
        .full(),
        .empty()
    );

    assign gtx0_rx_data_fifo_vio_async_in_i = gtx0_rx_data_from_fifo_i[148:117];

    assign gtx0_rx_data_fifo_vio_sync_in_i = gtx0_rx_data_from_fifo_i[116:85];

    assign gtx0_fifo_ila_in_i = gtx0_rx_data_from_fifo_i[84:0];

 
    assign gtx1_rx_data_to_fifo_i={gtx1_rx_data_vio_async_in_i,gtx1_rx_data_vio_sync_in_i,gtx1_ila_in_i};

    rx_phase_align_fifo rx_phase_align_fifo_1_i 
    (
        .rst(gtx1_rx_system_reset_c),
        .wr_clk(gtx1_rxusrclk2_i),
        .rd_clk(rx_vio_ila_clk_i),
        .din(gtx1_rx_data_to_fifo_i),  
        .wr_en(1'b1),
        .rd_en(1'b1),
        .dout(gtx1_rx_data_from_fifo_i),  
        .full(),
        .empty()
    );

    assign gtx1_rx_data_fifo_vio_async_in_i = gtx1_rx_data_from_fifo_i[148:117];

    assign gtx1_rx_data_fifo_vio_sync_in_i = gtx1_rx_data_from_fifo_i[116:85];

    assign gtx1_fifo_ila_in_i = gtx1_rx_data_from_fifo_i[84:0];


    // assign resets for frame_gen modules
    assign  gtx0_tx_system_reset_c = !gtx0_txresetdone_r2 || user_tx_reset_i;
    assign  gtx1_tx_system_reset_c = !gtx1_txresetdone_r2 || user_tx_reset_i;

    // assign resets for frame_check modules
    assign  gtx0_rx_system_reset_c = !gtx0_rxresetdone_r3 || user_rx_reset_i;
    assign  gtx1_rx_system_reset_c = !gtx1_rxresetdone_r3 || user_rx_reset_i;

    assign  gtx0_gtxrxreset_i = gtxrxreset_i || gtxtxreset_i;
    assign  gtx0_gtxtxreset_i = gtxrxreset_i || gtxtxreset_i;
    assign  gtx1_gtxrxreset_i = gtxrxreset_i || gtxtxreset_i;
    assign  gtx1_gtxtxreset_i = gtxrxreset_i || gtxtxreset_i;

    // Shared VIO Outputs
    assign  gtxtxreset_i                         =  shared_vio_out_i[31];
    assign  gtxrxreset_i                         =  shared_vio_out_i[30];
    assign  user_tx_reset_i                      =  shared_vio_out_i[29];
    assign  user_rx_reset_i                      =  shared_vio_out_i[28];
    assign  mux_sel_i                            =  shared_vio_out_i[27];

    // Shared VIO Inputs
    assign  shared_vio_in_i[31:0]                =  32'b00000000000000000000000000000000;

    // Chipscope connections on GTX 0
    assign  gtx0_tx_data_vio_async_in_i[31]      =  1'b0;
    assign  gtx0_tx_data_vio_async_in_i[30]      =  gtx0_txresetdone_i;
    assign  gtx0_tx_data_vio_async_in_i[29:0]    =  30'b000000000000000000000000000000;
    assign  gtx0_tx_data_vio_sync_in_i[31:0]     =  32'b00000000000000000000000000000000;
    assign  gtx0_txpllrefseldy_i                 =  tx_data_vio_async_out_i[30:28];
    assign  gtx0_loopback_i                      =  tx_data_vio_async_out_i[27:25];
    assign  gtx0_txdiffctrl_i                    =  tx_data_vio_async_out_i[24:21];
    assign  gtx0_txpreemphasis_i                 =  tx_data_vio_async_out_i[20:17];
    assign  gtx0_txpostemphasis_i                =  tx_data_vio_async_out_i[16:12];
    assign  gtx0_rx_data_vio_async_in_i[31]      =  gtx0_rxplllkdet_i;
    assign  gtx0_rx_data_vio_async_in_i[30]      =  gtx0_rxresetdone_i;
    assign  gtx0_rx_data_vio_async_in_i[29:0]    =  30'b000000000000000000000000000000;
    assign  gtx0_rx_data_vio_sync_in_i[31:0]     =  32'b00000000000000000000000000000000;
    assign  gtx0_pllrxreset_i                    =  rx_data_vio_async_out_i[31];
    assign  gtx0_rxpllrefseldy_i                 =  rx_data_vio_async_out_i[30:28];
    assign  gtx0_rxeqmix_i                       =  rx_data_vio_async_out_i[27:25];
    assign  gtx0_ila_in_i[84:83]                 =  gtx0_rxchariscomma_i;
    assign  gtx0_ila_in_i[82:81]                 =  gtx0_rxcharisk_i;
    assign  gtx0_ila_in_i[80:79]                 =  gtx0_rxdisperr_i;
    assign  gtx0_ila_in_i[78:77]                 =  gtx0_rxnotintable_i;
    assign  gtx0_ila_in_i[76]                    =  gtx0_rxchanbondseq_i;
    assign  gtx0_ila_in_i[75]                    =  gtx0_rxcommadet_i;
    assign  gtx0_ila_in_i[74:59]                 =  gtx0_rxdata_i;
    assign  gtx0_ila_in_i[58:56]                 =  gtx0_rxbufstatus_i;
    assign  gtx0_ila_in_i[55]                    =  gtx0_rxchanisaligned_i;
    assign  gtx0_ila_in_i[54]                    =  gtx0_rxchanrealign_i;
    assign  gtx0_ila_in_i[53:46]                 =  gtx0_error_count_i;
    assign  gtx0_ila_in_i[45:0]                  =  46'b0000000000000000000000000000000000000000000000;

    // Chipscope connections on GTX 1
    assign  gtx1_tx_data_vio_async_in_i[31]      =  1'b0;
    assign  gtx1_tx_data_vio_async_in_i[30]      =  gtx1_txresetdone_i;
    assign  gtx1_tx_data_vio_async_in_i[29:0]    =  30'b000000000000000000000000000000;
    assign  gtx1_tx_data_vio_sync_in_i[31:0]     =  32'b00000000000000000000000000000000;
    assign  gtx1_txpllrefseldy_i                 =  tx_data_vio_async_out_i[30:28];
    assign  gtx1_loopback_i                      =  tx_data_vio_async_out_i[27:25];
    assign  gtx1_txdiffctrl_i                    =  tx_data_vio_async_out_i[24:21];
    assign  gtx1_txpreemphasis_i                 =  tx_data_vio_async_out_i[20:17];
    assign  gtx1_txpostemphasis_i                =  tx_data_vio_async_out_i[16:12];
    assign  gtx1_rx_data_vio_async_in_i[31]      =  gtx1_rxplllkdet_i;
    assign  gtx1_rx_data_vio_async_in_i[30]      =  gtx1_rxresetdone_i;
    assign  gtx1_rx_data_vio_async_in_i[29:0]    =  30'b000000000000000000000000000000;
    assign  gtx1_rx_data_vio_sync_in_i[31:0]     =  32'b00000000000000000000000000000000;
    assign  gtx1_pllrxreset_i                    =  rx_data_vio_async_out_i[31];
    assign  gtx1_rxpllrefseldy_i                 =  rx_data_vio_async_out_i[30:28];
    assign  gtx1_rxeqmix_i                       =  rx_data_vio_async_out_i[27:25];
    assign  gtx1_ila_in_i[84:83]                 =  gtx1_rxchariscomma_i;
    assign  gtx1_ila_in_i[82:81]                 =  gtx1_rxcharisk_i;
    assign  gtx1_ila_in_i[80:79]                 =  gtx1_rxdisperr_i;
    assign  gtx1_ila_in_i[78:77]                 =  gtx1_rxnotintable_i;
    assign  gtx1_ila_in_i[76]                    =  gtx1_rxchanbondseq_i;
    assign  gtx1_ila_in_i[75]                    =  gtx1_rxcommadet_i;
    assign  gtx1_ila_in_i[74:59]                 =  gtx1_rxdata_i;
    assign  gtx1_ila_in_i[58:56]                 =  gtx1_rxbufstatus_i;
    assign  gtx1_ila_in_i[55]                    =  gtx1_rxchanisaligned_i;
    assign  gtx1_ila_in_i[54]                    =  gtx1_rxchanrealign_i;
    assign  gtx1_ila_in_i[53:46]                 =  gtx1_error_count_i;
    assign  gtx1_ila_in_i[45:0]                  =  46'b0000000000000000000000000000000000000000000000;


    //Mux inputs to Chipscope modules based on mux_sel_i

    assign  tx_data_vio_async_in_i =    (mux_sel_i == 1'b0)?gtx0_tx_data_vio_async_in_i:
                                                            gtx1_tx_data_vio_async_in_i;


    assign  tx_data_vio_sync_in_i =     (mux_sel_i == 1'b0)?gtx0_tx_data_vio_sync_in_i:
                                                            gtx1_tx_data_vio_sync_in_i;

    assign  rx_data_vio_async_in_i =    (mux_sel_i == 1'b0)?gtx0_rx_data_fifo_vio_async_in_i:
                                                            gtx1_rx_data_fifo_vio_async_in_i;


    assign  rx_data_vio_sync_in_i =     (mux_sel_i == 1'b0)?gtx0_rx_data_fifo_vio_sync_in_i:
                                                            gtx1_rx_data_fifo_vio_sync_in_i;


    assign  ila_in_i =                  (mux_sel_i == 1'b0)?gtx0_fifo_ila_in_i:
                                                            gtx1_fifo_ila_in_i;

end //end EXAMPLE_USE_CHIPSCOPE=1 generate section
else 
begin: no_chipscope

    // If Chipscope is not being used, drive GTX reset signal
    // from the top level ports
    assign  gtx0_gtxrxreset_i = GTXRXRESET_IN;
    assign  gtx0_gtxtxreset_i = GTXTXRESET_IN;
    assign  gtx1_gtxrxreset_i = GTXRXRESET_IN;
    assign  gtx1_gtxtxreset_i = GTXTXRESET_IN;

    // assign resets for frame_gen modules
    assign  gtx0_tx_system_reset_c = !gtx0_txresetdone_r2;
    assign  gtx1_tx_system_reset_c = !gtx1_txresetdone_r2;

    // assign resets for frame_check modules
    assign  gtx0_rx_system_reset_c = !gtx0_rxresetdone_r3;
    assign  gtx1_rx_system_reset_c = !gtx1_rxresetdone_r3;

    assign  gtxtxreset_i                         =  tied_to_ground_i;
    assign  gtxrxreset_i                         =  tied_to_ground_i;
    assign  user_tx_reset_i                      =  tied_to_ground_i;
    assign  user_rx_reset_i                      =  tied_to_ground_i;
    assign  mux_sel_i                            =  tied_to_ground_i;
    assign  gtx0_txpllrefseldy_i                 =  tied_to_ground_vec_i[2:0];
    assign  gtx0_loopback_i                      =  tied_to_ground_vec_i[2:0];
    assign  gtx0_txdiffctrl_i                    =  4'b1010;
    assign  gtx0_txpreemphasis_i                 =  tied_to_ground_vec_i[3:0];
    assign  gtx0_txpostemphasis_i                =  tied_to_ground_vec_i[4:0];
    assign  gtx0_pllrxreset_i                    =  tied_to_ground_i;
    assign  gtx0_rxpllrefseldy_i                 =  tied_to_ground_vec_i[2:0];
    assign  gtx0_rxeqmix_i                       =  tied_to_ground_vec_i[2:0];
    assign  gtx1_txpllrefseldy_i                 =  tied_to_ground_vec_i[2:0];
    assign  gtx1_loopback_i                      =  tied_to_ground_vec_i[2:0];
    assign  gtx1_txdiffctrl_i                    =  4'b1010;
    assign  gtx1_txpreemphasis_i                 =  tied_to_ground_vec_i[3:0];
    assign  gtx1_txpostemphasis_i                =  tied_to_ground_vec_i[4:0];
    assign  gtx1_pllrxreset_i                    =  tied_to_ground_i;
    assign  gtx1_rxpllrefseldy_i                 =  tied_to_ground_vec_i[2:0];
    assign  gtx1_rxeqmix_i                       =  tied_to_ground_vec_i[2:0];


end
endgenerate //End generate for EXAMPLE_USE_CHIPSCOPE


endmodule

//-------------------------------------------------------------------
//
//  VIO core module declaration
//
//-------------------------------------------------------------------
module data_vio
  (
    control,
    clk,
    async_in,
    async_out,
    sync_in,
    sync_out
  );
  inout  [35:0] control;
  input         clk;
  input  [31:0] async_in;
  output [31:0] async_out;
  input  [31:0] sync_in;
  output [31:0] sync_out;
endmodule


//-------------------------------------------------------------------
//
//  ICON core module declaration
//
//-------------------------------------------------------------------
module icon
  (
      control0,
      control1,
      control2,
      control3
  );
  inout [35:0] control0;
  inout [35:0] control1;
  inout [35:0] control2;
  inout [35:0] control3;
endmodule


//-------------------------------------------------------------------
//
//  ILA core module declaration
//  This is used to allow RX signals to be monitored
//
//-------------------------------------------------------------------
module ila
  (
    control,
    clk,
    trig0
  );
  inout [35:0] control;
  input clk;
  input [84:0] trig0;
endmodule

module rx_phase_align_fifo
  (
    rst,
    wr_clk,
    rd_clk,
    din,
    wr_en,
    rd_en,
    dout,
    full,
    empty
  );


  input rst;
  input wr_clk;
  input rd_clk;
  input [148:0] din;
  input wr_en;
  input rd_en;
  output [148:0] dout;
  output full;
  output empty;
endmodule 

