///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 1.12
//  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard
//  /   /         Filename : gtx_2links.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module GTX_2LINKS (a GTX Wrapper)
// Generated by Xilinx Virtex-6 FPGA GTX Transceiver Wizard
// 
// 
// (c) Copyright 2009-2011 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps


//***************************** Entity Declaration ****************************

(* CORE_GENERATION_INFO = "gtx_2links,v6_gtxwizard_v1_12,{protocol_file=Start_from_scratch}" *) module gtx_2links #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTXRESET_SPEEDUP    = 0    // Set to 1 to speed up sim reset
)
(
    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y9)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX0_LOOPBACK_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX0_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX0_RXCHARISK_OUT,
    output  [1:0]   GTX0_RXDISPERR_OUT,
    output  [1:0]   GTX0_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX0_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX0_RXCHBONDI_IN,
    input   [2:0]   GTX0_RXCHBONDLEVEL_IN,
    input           GTX0_RXCHBONDMASTER_IN,
    output  [3:0]   GTX0_RXCHBONDO_OUT,
    input           GTX0_RXCHBONDSLAVE_IN,
    input           GTX0_RXENCHANSYNC_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX0_RXBYTEISALIGNED_OUT,
    output          GTX0_RXCOMMADET_OUT,
    input           GTX0_RXENMCOMMAALIGN_IN,
    input           GTX0_RXENPCOMMAALIGN_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX0_RXDATA_OUT,
    output          GTX0_RXRECCLK_OUT,
    input           GTX0_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX0_RXEQMIX_IN,
    input           GTX0_RXN_IN,
    input           GTX0_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    output  [2:0]   GTX0_RXBUFSTATUS_OUT,
    output          GTX0_RXCHANISALIGNED_OUT,
    output          GTX0_RXCHANREALIGN_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX0_GREFCLKRX_IN,
    input           GTX0_GTXRXRESET_IN,
    input   [1:0]   GTX0_MGTREFCLKRX_IN,
    input   [1:0]   GTX0_NORTHREFCLKRX_IN,
    input           GTX0_PERFCLKRX_IN,
    input           GTX0_PLLRXRESET_IN,
    output          GTX0_RXPLLLKDET_OUT,
    input   [2:0]   GTX0_RXPLLREFSELDY_IN,
    output          GTX0_RXRESETDONE_OUT,
    input   [1:0]   GTX0_SOUTHREFCLKRX_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX0_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX0_TXDATA_IN,
    output          GTX0_TXOUTCLK_OUT,
    input           GTX0_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX0_TXDIFFCTRL_IN,
    output          GTX0_TXN_OUT,
    output          GTX0_TXP_OUT,
    input   [4:0]   GTX0_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX0_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX0_GREFCLKTX_IN,
    input           GTX0_GTXTXRESET_IN,
    input   [1:0]   GTX0_NORTHREFCLKTX_IN,
    input           GTX0_PERFCLKTX_IN,
    input   [1:0]   GTX0_SOUTHREFCLKTX_IN,
    input   [2:0]   GTX0_TXPLLREFSELDY_IN,
    output          GTX0_TXRESETDONE_OUT,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y11)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX1_LOOPBACK_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX1_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX1_RXCHARISK_OUT,
    output  [1:0]   GTX1_RXDISPERR_OUT,
    output  [1:0]   GTX1_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX1_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX1_RXCHBONDI_IN,
    input   [2:0]   GTX1_RXCHBONDLEVEL_IN,
    input           GTX1_RXCHBONDMASTER_IN,
    output  [3:0]   GTX1_RXCHBONDO_OUT,
    input           GTX1_RXCHBONDSLAVE_IN,
    input           GTX1_RXENCHANSYNC_IN,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX1_RXBYTEISALIGNED_OUT,
    output          GTX1_RXCOMMADET_OUT,
    input           GTX1_RXENMCOMMAALIGN_IN,
    input           GTX1_RXENPCOMMAALIGN_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX1_RXDATA_OUT,
    output          GTX1_RXRECCLK_OUT,
    input           GTX1_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input   [2:0]   GTX1_RXEQMIX_IN,
    input           GTX1_RXN_IN,
    input           GTX1_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    output  [2:0]   GTX1_RXBUFSTATUS_OUT,
    output          GTX1_RXCHANISALIGNED_OUT,
    output          GTX1_RXCHANREALIGN_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX1_GREFCLKRX_IN,
    input           GTX1_GTXRXRESET_IN,
    input   [1:0]   GTX1_MGTREFCLKRX_IN,
    input   [1:0]   GTX1_NORTHREFCLKRX_IN,
    input           GTX1_PERFCLKRX_IN,
    input           GTX1_PLLRXRESET_IN,
    output          GTX1_RXPLLLKDET_OUT,
    input   [2:0]   GTX1_RXPLLREFSELDY_IN,
    output          GTX1_RXRESETDONE_OUT,
    input   [1:0]   GTX1_SOUTHREFCLKRX_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX1_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX1_TXDATA_IN,
    output          GTX1_TXOUTCLK_OUT,
    input           GTX1_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX1_TXDIFFCTRL_IN,
    output          GTX1_TXN_OUT,
    output          GTX1_TXP_OUT,
    input   [4:0]   GTX1_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX1_TXPREEMPHASIS_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX1_GREFCLKTX_IN,
    input           GTX1_GTXTXRESET_IN,
    input   [1:0]   GTX1_NORTHREFCLKTX_IN,
    input           GTX1_PERFCLKTX_IN,
    input   [1:0]   GTX1_SOUTHREFCLKTX_IN,
    input   [2:0]   GTX1_TXPLLREFSELDY_IN,
    output          GTX1_TXRESETDONE_OUT


);

//***************************** Wire Declarations *****************************

    // ground and vcc signals
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [63:0]  tied_to_vcc_vec_i;
 
//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


//------------------------- GTX Instances  -------------------------------



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y9)

    gtx_2links_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110100)
    )
    gtx0_gtx_2links_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX0_LOOPBACK_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX0_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX0_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX0_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX0_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX0_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX0_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX0_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX0_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX0_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX0_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX0_RXENCHANSYNC_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX0_RXBYTEISALIGNED_OUT),
        .RXCOMMADET_OUT                 (GTX0_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX0_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX0_RXENPCOMMAALIGN_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX0_RXDATA_OUT),
        .RXRECCLK_OUT                   (GTX0_RXRECCLK_OUT),
        .RXUSRCLK2_IN                   (GTX0_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX0_RXEQMIX_IN),
        .RXN_IN                         (GTX0_RXN_IN),
        .RXP_IN                         (GTX0_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFSTATUS_OUT                (GTX0_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX0_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX0_RXCHANREALIGN_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GREFCLKRX_IN                   (GTX0_GREFCLKRX_IN),
        .GTXRXRESET_IN                  (GTX0_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 (GTX0_MGTREFCLKRX_IN),
        .NORTHREFCLKRX_IN               (GTX0_NORTHREFCLKRX_IN),
        .PERFCLKRX_IN                   (GTX0_PERFCLKRX_IN),
        .PLLRXRESET_IN                  (GTX0_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX0_RXPLLLKDET_OUT),
        .RXPLLREFSELDY_IN               (GTX0_RXPLLREFSELDY_IN),
        .RXRESETDONE_OUT                (GTX0_RXRESETDONE_OUT),
        .SOUTHREFCLKRX_IN               (GTX0_SOUTHREFCLKRX_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX0_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX0_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX0_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX0_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX0_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX0_TXN_OUT),
        .TXP_OUT                        (GTX0_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX0_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX0_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GREFCLKTX_IN                   (GTX0_GREFCLKTX_IN),
        .GTXTXRESET_IN                  (GTX0_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 (GTX0_MGTREFCLKRX_IN),
        .NORTHREFCLKTX_IN               (GTX0_NORTHREFCLKTX_IN),
        .PERFCLKTX_IN                   (GTX0_PERFCLKTX_IN),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .SOUTHREFCLKTX_IN               (GTX0_SOUTHREFCLKTX_IN),
        .TXPLLLKDET_OUT                 (),
        .TXPLLREFSELDY_IN               (GTX0_TXPLLREFSELDY_IN),
        .TXRESETDONE_OUT                (GTX0_TXRESETDONE_OUT)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y11)

    gtx_2links_gtx #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),
        
        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000110100)
    )
    gtx1_gtx_2links_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX1_LOOPBACK_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX1_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX1_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX1_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX1_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX1_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX1_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX1_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX1_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX1_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX1_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX1_RXENCHANSYNC_IN),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX1_RXBYTEISALIGNED_OUT),
        .RXCOMMADET_OUT                 (GTX1_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX1_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX1_RXENPCOMMAALIGN_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX1_RXDATA_OUT),
        .RXRECCLK_OUT                   (GTX1_RXRECCLK_OUT),
        .RXUSRCLK2_IN                   (GTX1_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXEQMIX_IN                     (GTX1_RXEQMIX_IN),
        .RXN_IN                         (GTX1_RXN_IN),
        .RXP_IN                         (GTX1_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFSTATUS_OUT                (GTX1_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX1_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX1_RXCHANREALIGN_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GREFCLKRX_IN                   (GTX1_GREFCLKRX_IN),
        .GTXRXRESET_IN                  (GTX1_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 (GTX1_MGTREFCLKRX_IN),
        .NORTHREFCLKRX_IN               (GTX1_NORTHREFCLKRX_IN),
        .PERFCLKRX_IN                   (GTX1_PERFCLKRX_IN),
        .PLLRXRESET_IN                  (GTX1_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX1_RXPLLLKDET_OUT),
        .RXPLLREFSELDY_IN               (GTX1_RXPLLREFSELDY_IN),
        .RXRESETDONE_OUT                (GTX1_RXRESETDONE_OUT),
        .SOUTHREFCLKRX_IN               (GTX1_SOUTHREFCLKRX_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX1_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX1_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX1_TXOUTCLK_OUT),
        .TXUSRCLK2_IN                   (GTX1_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX1_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX1_TXN_OUT),
        .TXP_OUT                        (GTX1_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX1_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX1_TXPREEMPHASIS_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GREFCLKTX_IN                   (GTX1_GREFCLKTX_IN),
        .GTXTXRESET_IN                  (GTX1_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 (GTX1_MGTREFCLKRX_IN),
        .NORTHREFCLKTX_IN               (GTX1_NORTHREFCLKTX_IN),
        .PERFCLKTX_IN                   (GTX1_PERFCLKTX_IN),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .SOUTHREFCLKTX_IN               (GTX1_SOUTHREFCLKTX_IN),
        .TXPLLLKDET_OUT                 (),
        .TXPLLREFSELDY_IN               (GTX1_TXPLLREFSELDY_IN),
        .TXRESETDONE_OUT                (GTX1_TXRESETDONE_OUT)

    );



endmodule

    
